chess_rob:

  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 100

  arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3


    gains:
      joint_1: {p: 1,  d: 1, i: 1}
      joint_2: {p: 1,  d: 1, i: 1}
      joint_3: {p: 1,  d: 1, i: 1}
